version: "3.8"

services:
  web:
    build: .
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    working_dir: /usr/src/app/
    env_file:
      - ./.env.prod
    volumes:
      - ./:/usr/src/app/
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: postgres:14.4-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=/run/secrets/db_username
      - MYSQL_PASSWORD=/run/secrets/db_password
      - MYSQL_DATABASE=/run/secrets/db_name

secrets:
  db_username:
    file: db_username.txt
  db_password:
    file: db_password.txt
  db_name:
    file: db_name.txt
